### PANDAS & NUMPY


In [2]:
import numpy as np

In [3]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr = np.ones((3,6))

In [6]:
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
arr.dtype

dtype('float64')

In [8]:
l = [2,3,3,23,0,1]

In [9]:
np_arr = np.array(1)

In [11]:
np_arr.dtype

dtype('int32')

In [15]:
data = np.random.randn(7,4)

In [16]:
data

array([[-0.40341674,  0.23651834,  0.60542102, -0.93136661],
       [-0.38183448,  0.0370271 ,  0.65517759, -0.12445178],
       [ 1.62525628, -0.59025164, -0.2956923 ,  1.48769159],
       [-0.40649326,  0.28766957, -0.07387112,  0.21233388],
       [-0.20616584,  1.99915383, -0.38264173, -0.27111316],
       [-2.14653909,  0.35529904, -0.09212888, -0.53390495],
       [-0.36031633,  1.20235485, -0.81000836,  0.10757184]])

In [19]:
a = np.array ([[1, 2, 3,],[4, 5, 6,],[7, 8, 9]])

In [7]:
b = np.array ([[9, 2, 3], [7, -2, 9],[4, 16, 36], [8, 9, 3]])

In [25]:
a.shape

(3, 3)

In [26]:
b.shape

(4, 3)

In [28]:
b=b.reshape(3,4)

In [29]:
b.shape

(3, 4)

In [30]:
a.dot(b)

array([[113,  44,  38,  48],
       [242, 101,  86, 126],
       [371, 158, 134, 204]])

In [32]:
a.sum()

45

In [14]:
import numpy as np

In [15]:
a = np.array ([[1, 2, 3,],[4, 5, 6,],[7, 8, 9]])

In [16]:
b = np.array ([[9, 2, 3], [7, -2, 9],[4, 16, 36]])

In [17]:
a.shape

(3, 3)

In [18]:
b.shape

(3, 3)

In [19]:
b=b.reshape(3,3)

In [20]:
b.shape

(3, 3)

In [21]:
a.dot(b)

array([[ 35,  46, 129],
       [ 95,  94, 273],
       [155, 142, 417]])

In [22]:
a.sum()

45

In [23]:
b.sum()

84

In [24]:
a.mean()

5.0

In [25]:
b.mean()

9.333333333333334

In [27]:
np.sqrt(b)

C:\Users\MAJORN~1\AppData\Local\Temp/ipykernel_13148/3240365511.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(b)


array([[3.        , 1.41421356, 1.73205081],
       [2.64575131,        nan, 3.        ],
       [2.        , 4.        , 6.        ]])

In [28]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [29]:
b=b.reshape(3,3)

In [30]:
b.shape

(3, 3)

In [31]:
b=b.reshape(3,3)

In [32]:
a.sort(axis=1)

In [33]:
a.shape

(3, 3)

In [34]:
a/b

array([[ 0.11111111,  1.        ,  1.        ],
       [ 0.57142857, -2.5       ,  0.66666667],
       [ 1.75      ,  0.5       ,  0.25      ]])

In [35]:
np.multiply(a,b)

array([[  9,   4,   9],
       [ 28, -10,  54],
       [ 28, 128, 324]])

In [36]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [37]:
np.log(b)

C:\Users\MAJORN~1\AppData\Local\Temp/ipykernel_13148/4200754868.py:1: RuntimeWarning: invalid value encountered in log
  np.log(b)


array([[2.19722458, 0.69314718, 1.09861229],
       [1.94591015,        nan, 2.19722458],
       [1.38629436, 2.77258872, 3.58351894]])

In [38]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [39]:
np.cos(b)

array([[-0.91113026, -0.41614684, -0.9899925 ],
       [ 0.75390225, -0.41614684, -0.91113026],
       [-0.65364362, -0.95765948, -0.12796369]])

In [42]:
a==b

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [41]:
b+a

array([[10,  4,  6],
       [11,  3, 15],
       [11, 24, 45]])

In [43]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [44]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])